project:
  type: website

website:
  title: "Boudry Felix"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: publications.qmd
        text: Publications
      - href: talks.qmd
        text: Talks
      - href: lessons.qmd
        text: Lessons
      - text: Softwares
        menu:
          - href: softwares.qmd
            text: Overview
          - href: softwares.html?app=prescription
            text: Prescription generator
          - href: softwares.html?app=load-velocity
            text: Load-velocity model
      - href: about.qmd
        text: About

format:
  html:
    theme:
      dark: darkly
      light: cosmo
    toc: true



